import os

import pytest

from pathlib import Path

from app import app, all_documents, check_admin_credentials, delete_document_file, delete_document_record, safe_redirect_target, site_settings
from document_generation import document_generator_catalog, render_document_pdf, validate_generator_payload


@pytest.fixture(autouse=True)
def reset_login_attempts() -> None:
    app.extensions.pop("login_attempts", None)
    yield
    app.extensions.pop("login_attempts", None)


@pytest.fixture
def client() -> object:
    return app.test_client()


def authenticated_client(client) -> object:
    with client.session_transaction() as session:
        session["is_admin"] = True
        session["admin_username"] = app.config["ADMIN_USERNAME"]
        session["_csrf_token"] = "test-token"
    return client


def billing_document_payload() -> dict[str, str]:
    return {
        "csrf_token": "test-token",
        "template_key": "billing",
        "title": "QA Billing Document",
        "resident_name": "QA Client",
        "unit_reference": "QA-UNIT-001",
        "property_title": "QA Test Property",
        "note": "Generated by automated tests.",
        "guided_issue_date": "2026-06-15",
        "guided_document_number": "QA-INV-001",
        "guided_due_date": "2026-06-30",
        "guided_currency": "NGN",
        "guided_bill_to_name": "QA Client",
        "guided_bill_to_company": "QA Holdings",
        "guided_bill_to_address_lines": "Victoria Island\nLagos",
        "guided_line_items": "Management fee | 1 | 250000\nService charge | 2 | 150000",
        "guided_payment_instructions": "Pay to Structurebase client account\nUse invoice reference",
        "guided_notes": "Generated as a regression test.",
        "guided_terms": "Payment due before the stated due date.",
    }


def test_healthz_returns_ok(client) -> None:
    response = client.get("/healthz")

    assert response.status_code == 200
    payload = response.get_json()
    assert payload["status"] == "ok"


def test_safe_redirect_target_rejects_external_redirects() -> None:
    with app.test_request_context("/login?next=https://evil.example.com"):
        assert safe_redirect_target("https://evil.example.com") == "/dashboard"


def test_login_success_redirects_to_dashboard(client) -> None:
    with client.session_transaction() as session:
        session["_csrf_token"] = "test-token"

    response = client.post(
        "/login",
        data={
            "username": app.config["ADMIN_USERNAME"],
            "password": app.config["ADMIN_PASSWORD"],
            "csrf_token": "test-token",
        },
        follow_redirects=False,
    )

    assert response.status_code == 302
    assert response.headers["Location"] == "/dashboard"


def test_login_rate_limit_blocks_after_five_failures(client) -> None:
    for _ in range(5):
        with client.session_transaction() as session:
            session["_csrf_token"] = "test-token"

        response = client.post(
            "/login",
            data={
                "username": "admin",
                "password": "wrong-password",
                "csrf_token": "test-token",
            },
            follow_redirects=False,
        )

        assert response.status_code in {200, 302}

    response = client.post(
        "/login",
        data={
            "username": "admin",
            "password": "wrong-password",
            "csrf_token": "test-token",
        },
        follow_redirects=False,
    )

    assert response.status_code == 200
    assert b"Too many sign-in attempts" in response.data


def test_production_rejects_default_admin_password(monkeypatch) -> None:
    monkeypatch.setitem(app.config, "IS_PRODUCTION", True)
    monkeypatch.setitem(app.config, "ADMIN_USERNAME", "admin")
    monkeypatch.setitem(app.config, "ADMIN_PASSWORD", "change-me-structurebase")
    monkeypatch.setitem(app.config, "ADMIN_PASSWORD_HASH", "")

    assert check_admin_credentials("admin", "change-me-structurebase") is False


def test_document_preview_returns_pdf_without_saving(client) -> None:
    authenticated_client(client)
    with app.app_context():
        before = {document["id"] for document in all_documents()}

    response = client.post("/dashboard/documents/preview", data=billing_document_payload())

    with app.app_context():
        after = {document["id"] for document in all_documents()}
    assert response.status_code == 200
    assert response.mimetype == "application/pdf"
    assert response.data.startswith(b"%PDF-")
    assert after == before


def test_generated_document_saves_as_final_and_cleans_up(client) -> None:
    authenticated_client(client)
    with app.app_context():
        before = {document["id"] for document in all_documents()}

    response = client.post("/dashboard/documents/generate", data=billing_document_payload(), follow_redirects=False)

    with app.app_context():
        created = [document for document in all_documents() if document["id"] not in before]
    try:
        assert response.status_code == 302
        assert response.headers["Location"] == "/dashboard/documents"
        assert len(created) == 1
        assert created[0]["document_status"] == "Final"
        assert created[0]["source_kind"] == "generated"
        assert created[0]["payload_data"]["document_status"] == "Final"
    finally:
        with app.app_context():
            for document in created:
                deleted = delete_document_record(document["id"])
                delete_document_file(deleted.get("stored_filename"))


def test_all_document_templates_render_sample_pdfs(tmp_path: Path) -> None:
    with app.app_context():
        settings = site_settings()
        catalog = document_generator_catalog(settings)
        for key, template in catalog.items():
            payload, errors = validate_generator_payload(key, template["sample_payload"], settings)
            assert errors == []
            destination = tmp_path / f"{key}.pdf"
            render_document_pdf(key, f"QA {template['label']}", payload, destination, settings)
            assert destination.read_bytes().startswith(b"%PDF-")
            assert destination.stat().st_size > 10_000


def test_generated_pdfs_do_not_expose_internal_template_labels(tmp_path: Path) -> None:
    from pypdf import PdfReader

    with app.app_context():
        settings = site_settings()
        catalog = document_generator_catalog(settings)
        for key in ("letterhead", "maintenance_work_order"):
            template = catalog[key]
            internal_title = f"QA {template['label']} - Structurebase"
            payload, errors = validate_generator_payload(key, template["sample_payload"], settings)
            assert errors == []
            destination = tmp_path / f"{key}.pdf"
            render_document_pdf(key, internal_title, payload, destination, settings)
            text = "\n".join(page.extract_text() or "" for page in PdfReader(str(destination)).pages)
            assert internal_title not in text
            assert "Preview document" not in text
            assert "Final document" not in text
            assert "Generated " not in text


def test_legal_templates_include_compliance_controls() -> None:
    with app.app_context():
        settings = site_settings()
        catalog = document_generator_catalog(settings)
        for key in ("tenancy_agreement", "sale_agreement", "lease_notice", "management_agreement"):
            payload, errors = validate_generator_payload(key, catalog[key]["sample_payload"], settings)
            assert errors == []
            assert payload["legal_basis"]
            assert payload["statutory_notes"]
            assert payload["execution_notes"]
            assert payload["governing_law"]
            assert payload["lawyer_review_note"]
